version: '3.8'

services:
  backend:
    image: tisncutee/cloud-lab-backend:1.0  # (Câu 51)
    ports:
      - "5000:5000"  # (Câu 53)
    environment:
      - MONGODB_URI=mongodb+srv://leduonghuynhtinpt123_db_user:12092004@cluster0.rvcavaf.mongodb.net/cloud_lab?appName=Cluster0 # (Câu 55)
      - PORT=5000

  frontend:
    image: tisncutee/cloud-lab-frontend:1.0 # (Câu 52)
    ports:
      - "5173:5173"  # (Câu 54)
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend